version: "2"

run:
  timeout: 5m
  tests: true
  build-tags:
    - acc

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/Trozz/terraform-provider-pocketid

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
