version: "2"

run:
  timeout: 5m
  tests: true
  build-tags:
    - acc

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/Trozz/terraform-provider-pocketid

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
