# .golangci.yml
# Minimal configuration to avoid compatibility issues

run:
  timeout: 5m
  tests: true
  build-tags:
    - acc

linters:
  disable-all: true
  enable:
    # Enable only stable, essential linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/Trozz/terraform-provider-pocketid

issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0

  # Exclude some linters from running on tests files.
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
