# Markdownlint configuration
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Disable some overly strict rules
MD033: false  # Inline HTML
MD041: false  # First line in file should be a top level header
MD024: false  # Multiple headers with the same content
MD036: false  # Emphasis used instead of a header

# Configure line length
MD013:
  line_length: 120
  code_blocks: false
  tables: false
