# Codecov configuration for Terraform PocketID Provider
# https://docs.codecov.com/docs/codecovyml-reference

# Coverage configuration
coverage:
  precision: 2
  round: down
  range: "30...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        paths:
          - "internal/"
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false

        # Commit status configuration
        flags:
          - unittests

      # Additional status check for overall project health
      project-health:
        target: 70%
        threshold: 5%
        paths:
          - "internal/"
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false

        # Status check settings
        flags:
          - unittests

      # Component-specific status checks
      client:
        target: 80%
        threshold: 5%
        paths:
          - "internal/client/**"
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false

      resources:
        target: 85%
        threshold: 5%
        paths:
          - "internal/resources/**"
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false

      datasources:
        target: 80%
        threshold: 5%
        paths:
          - "internal/datasources/**"
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false

    patch:
      default:
        target: 80%
        threshold: 10%
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false

        # Commit status configuration
        flags:
          - unittests

# Test analytics configuration
# https://docs.codecov.com/docs/test-analytics
test_analytics:
  enabled: true

# Components configuration for modular coverage tracking
# https://docs.codecov.com/docs/components
components:
  client:
    name: "API Client"
    paths:
      - "internal/client/**"

  datasources:
    name: "Data Sources"
    paths:
      - "internal/datasources/**"

  provider:
    name: "Provider Core"
    paths:
      - "internal/provider/**"

  resources:
    name: "Resources"
    paths:
      - "internal/resources/**"

  models:
    name: "Models"
    paths:
      - "internal/models/**"

# Flags configuration for different test types
flags:
  unittests:
    paths:
      - internal/
    carryforward: true
    components:
      - client
      - datasources
      - provider
      - resources
      - models

# Comment configuration
comment:
  layout: "reach,diff,flags,tree,betaprofiling"
  behavior: default
  require_changes: false
  require_base: true
  require_head: true
  show_carryforward_flags: true
  show_critical_paths: true

  # Test results in PR comments
  show_test_results: true

# Ignore certain files/paths
ignore:
  - "**/*_test.go"
  - "**/testdata/**"
  - "examples/**"
  - "docs/**"
  - "*.md"
  - "go.mod"
  - "go.sum"
  - ".github/**"
  - ".gitignore"
  - "LICENSE"
  - "Makefile"
  - ".golangci.yml"
  - ".goreleaser.yml"

# Parsers configuration
parsers:
  junit:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

# GitHub integration
github_checks:
  annotations: true

# Status checks configuration
status_checks:
  default_rules:
    flag_coverage_not_uploaded_behavior: include
    carryforward_behavior: include

# Codecov CI settings
codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true
