name: Pre-commit checks

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  pull-requests: read

jobs:
  conventional-commits:
    uses: ./.github/workflows/conventional-commits.yml
    if: github.event_name == 'pull_request'

  validation:
    uses: ./.github/workflows/validation.yml

  security:
    uses: ./.github/workflows/security.yml
