name: Validation

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: write

jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      markdown: ${{ steps.filter.outputs.markdown }}
      yaml: ${{ steps.filter.outputs.yaml }}
      json: ${{ steps.filter.outputs.json }}
      scripts: ${{ steps.filter.outputs.scripts }}
      terraform: ${{ steps.filter.outputs.terraform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4

      - name: Check for file changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            markdown:
              - '**/*.md'
              - '.markdownlint.yaml'
              - '.markdownlint-cli2.yaml'
            yaml:
              - '**/*.yml'
              - '**/*.yaml'
            json:
              - '**/*.json'
              - '**/*.jsonc'
            scripts:
              - 'scripts/**'
            terraform:
              - '**/*.tf'
              - '**/*.tfvars'
              - 'examples/**/*.hcl'

  file-validation:
    runs-on: ubuntu-latest
    name: File Validation
    needs: changes
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4

      - name: Check trailing whitespace
        run: ./scripts/validation/check-trailing-whitespace.sh

      - name: Check end-of-file newlines
        run: ./scripts/validation/check-newlines.sh

      - name: Check merge conflicts
        run: ./scripts/validation/check-merge-conflicts.sh

      - name: Validate YAML files
        if: needs.changes.outputs.yaml == 'true'
        run: ./scripts/validation/validate-yaml.sh

      - name: Validate JSON files
        if: needs.changes.outputs.json == 'true'
        run: ./scripts/validation/validate-json.sh

      - name: Check case conflicts
        run: ./scripts/validation/check-case-conflicts.sh

      - name: Check script permissions
        if: needs.changes.outputs.scripts == 'true'
        run: ./scripts/validation/check-script-permissions.sh

      - name: Check line endings
        run: ./scripts/validation/check-line-endings.sh

  markdown-lint:
    runs-on: ubuntu-latest
    name: Markdown Lint
    needs: changes
    if: needs.changes.outputs.markdown == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@992badcdf24e3b8eb7e87ff9287fe931bcb00c6e # v19
        with:
          fix: false
          globs: '**/*.md'

  terraform-fmt:
    runs-on: ubuntu-latest
    name: Terraform Format
    needs: changes
    if: needs.changes.outputs.terraform == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3

      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Comment PR on failure
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v7
        if: github.event_name == 'pull_request' && steps.fmt.outcome == 'failure'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `
            #### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`

            \`\`\`
            terraform fmt -check -recursive
            \`\`\`

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Format Status
        if: steps.fmt.outcome == 'failure'
        run: exit 1
